export const STEP_ITEM = [
  {
    id: 1,
    label: "Free Konsultasi",
    description:
      "Konsultasikan interior anda pada desainer kami secara gratis.",
    icon: "/assets/icon/freecon.png",
    iconWidth: 70,
    iconHeight: 70,
    src: "/assets/images/step/freeconsul.png",
    alt: "Image 1",
  },
  {
    id: 2,
    label: "Survey Lokasi",
    description: "Klien Memberikan ukuran ruangan",
    icon: "/assets/icon/surveylok.png",
    iconWidth: 70,
    iconHeight: 70,
    src: "/assets/images/step/surveyloc.png",
    alt: "Image 2",
  },
  {
    id: 3,
    label: "Proses Desain",
    description: "Menghasilkan desain 3D & gambaran kerja",
    icon: "/assets/icon/proses.png",
    iconWidth: 70,
    iconHeight: 70,
    src: "/assets/images/step/design.png",
    alt: "Image 4",
  },
  {
    id: 6,
    label: "Proposal Desain & RAB",
    description: "Pelaksanaan sesuai dengan Perjanjian & Kesepakatan ",
    icon: "/assets/icon/pelaksanaan.png",
    iconWidth: 70,
    iconHeight: 70,
    src: "/assets/images/step/rab.png",
    alt: "Image 5",
  },
  {
    id: 5,
    label: "Perjanjian & Kesepakatan",
    description: "Terdiri dari Perjanjian, Perencanaan, dan Pelaksanaan",
    icon: "/assets/icon/perjanjian.png",
    iconWidth: 70,
    iconHeight: 70,
    src: "/assets/images/step/deals.png",
    alt: "Image 6",
  },
  {
    id: 4,
    label: "Proses Pelaksanaan",
    description: "Pengajuan Desain dan Rencana Anggaran Biaya",
    icon: "/assets/icon/proposal.png",
    iconWidth: 70,
    iconHeight: 70,
    src: "/assets/images/step/execution.png",
    alt: "Image 7",
  },
  {
    id: 7,
    label: "Pelayanan Purna Jual",
    description:
      "Jaminan pemeliharaan sesuai dengan garansi paket yang dipilih",
    icon: "/assets/icon/proses.png",
    iconWidth: 70,
    iconHeight: 70,
    src: "/assets/images/step/afterexecution.png",
    alt: "Image 8",
  },
];
