export const STEP_ITEM = [
  {
    id: 1,
    label: "Gratis Konsultasi",
    description:
      "Hubungi kami untuk mendapatkan konsultasi gratis dengan Konsultan Desain kami secara gratis.",
    icon: "/assets/icon/freecon.png",
    iconWidth: 70,
    iconHeight: 70,
    src: "/assets/images/step/freeconsul.png",
    alt: "Image 1",
  },
  {
    id: 2,
    label: "Survey Lokasi",
    description: "Jadwalkan kunjungan tim kami ke tempat Anda.",
    icon: "/assets/icon/surveylok.png",
    iconWidth: 70,
    iconHeight: 70,
    src: "/assets/images/step/surveyloc.png",
    alt: "Image 2",
  },
  {
    id: 3,
    label: "Proses Desain & Penyusunan RAB",
    description:
      "Setelah pembayaran Booking Fee, desainer kami akan mendesain ruang nyaman untuk anda disertai dengan harga terbaik dari tim keuangan kami.",
    icon: "/assets/icon/proposal.png",
    iconWidth: 70,
    iconHeight: 70,
    src: "/assets/images/step/design.png",
    alt: "Image 4",
  },
  // {
  //   id: 4,
  //   label: "Proses Pelaksanaan",
  //   description: "Pengajuan Desain dan Rencana Anggaran Biaya",
  //   icon: "/assets/icon/proposal.png",
  //   iconWidth: 70,
  //   iconHeight: 70,
  //   src: "/assets/images/step/execution.png",
  //   alt: "Image 7",
  // },
  {
    id: 4,
    label: "Proses Produksi",
    description:
      "Apabila desain dan RAB sudah disetujui, interior anda siap diproduksi oleh tim produksi terbaik kami. ",
    icon: "/assets/icon/perjanjian.png",
    iconWidth: 70,
    iconHeight: 70,
    src: "/assets/images/step/production.png",
    alt: "Image 6",
  },
  {
    id: 5,
    label: "Instalasi",
    description:
      "Proses Instalasi dilakukan setelah proses produksi di workshop kami telah selesai.",
    icon: "/assets/icon/pelaksanaan.png",
    iconWidth: 70,
    iconHeight: 70,
    src: "/assets/images/step/instalation.png",
    alt: "Image 5",
  },
  {
    id: 6,
    label: "Handover",
    description:
      "Akhirnya Interior ruanganmu sudah siap untuk digunakan! Tetap terasa aman dan nyaman dengan garansi selama 2 Tahun.",
    icon: "/assets/icon/purna.png",
    iconWidth: 70,
    iconHeight: 70,
    src: "/assets/images/step/aftersales.png",
    alt: "Image 8",
  },
];
